# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

perturb_cells_cpp <- function(count_matrix, damaged_cell_selections, damage_levels, non_mito_idx, gene_names, ribo_pattern, ribosome_penalty, seed) {
    .Call(`_DamageDetective_perturb_cells_cpp`, count_matrix, damaged_cell_selections, damage_levels, non_mito_idx, gene_names, ribo_pattern, ribosome_penalty, seed)
}

